language: node_js
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
node_js:
  - 5.0.0
services:
  - postgresql
before_script:
  - sudo adduser admin2
  - echo -e "test\ntest" | sudo passwd admin2 test
  - psql -c "create user admin2 with password 'test';" -U postgres
  - psql -c "create database likedb;" -U postgres
  - psql -c "grant all privileges on database likedb to admin2;" -U postgre
  - sleep 15
script:
  - npm test

after_script:
  - sleep 15
