language: node_js
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
node_js:
  - 5.0.0
services:
  - postgresql
before_script:
  - psql -c "create database likedb;" -U postgres
  - node ./test/server/dbSetup.js
  - sleep 15
script:
  - npm test

after_script:
  - sleep 15
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec ./test/test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
