language: node_js
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
node_js:
  - 5.0.0
services:
  - postgresql
before_script:
  - psql -c "create database likedb;" -U postgres
  - sleep 15
script:
  - npm test

after_script:
  - sleep 15
